name: Релиз проекта

on:
  workflow_dispatch:
    inputs:
      version:
        description: Версия релиза
        required: true
        type: string

jobs:
  changelog:
    uses: Pacific-Agency/workflows/.github/workflows/changelog.yml@v0.2.0
    with:
      version: ${{ inputs.version }}
    secrets:
      BOT_ACCESS_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

  publish:
    runs-on: ubuntu-latest
    needs: changelog
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Настройка NodeJS
        uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/

      - name: Публикация
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
